version: '3'
services:
  master:
    image: tmate/tmate-master:latest
    environment:
      HOSTNAME: master-0
      MASTER_BASE_URL: &master_base_url 'http://${EXTERNAL_FQDN}:4000/'
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      INTERNAL_API_AUTH_TOKEN: &internal_api_auth_token ${INTERNAL_API_AUTH_TOKEN}
      PG_URI: pg://tmate:${POSTGRES_PASSWORD}@postgres:5432/tmate
      ERL_NODE_NAME: erl_node_name
      ERL_COOKIE: erl_cookie
    env_file: [email.env]
    ports: ["0.0.0.0:4000:4000"]
    restart: unless-stopped
  ssh:
    image: tmate/tmate-ssh-server:latest
    environment:
      SSH_KEYS_PATH: /keys
      HAS_WEBSOCKET: 1
      SSH_HOSTNAME: ${EXTERNAL_FQDN}
      SSH_PORT_LISTEN: ${SSH_PORT}
      SSH_PORT_ADVERTISE: ${SSH_PORT}
    command: [-wwebsocket]
    volumes: ["$PWD/keys:/keys", "sessions:/tmp/tmate/sessions"]
    restart: unless-stopped
    ports: ["0.0.0.0:${SSH_PORT}:${SSH_PORT}"]
    cap_add: [SYS_ADMIN]
  websocket:
    image: tmate/tmate-websocket:latest
    environment:
      WEBSOCKET_BASE_URL: 'ws://${EXTERNAL_FQDN}:4001/'
      MASTER_BASE_URL: http://master:4000/
      USER_FACING_BASE_URL: *master_base_url
      DAEMON_HMAC_KEY: ${DAEMON_HMAC_KEY} 
      INTERNAL_API_AUTH_TOKEN: *internal_api_auth_token
      ERL_NODE_NAME: erl_node_name
      ERL_COOKIE: erl_cookie
    expose: [4002]
    volumes: ["sessions:/tmp/tmate/sessions"]
    ports: ["0.0.0.0:4001:4001"]
    restart: unless-stopped
  postgres:
    image: postgres:10
    environment:
      POSTGRES_USER: tmate
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: tmate
    volumes: ["postgres_data:/var/lib/postgresql/data"]
    restart: unless-stopped

volumes:
  postgres_data: {}
  sessions: {}
