apiVersion: v1
kind: PersistentVolume
metadata:
  name: synapse
  labels:
    app: synapse
spec:
  storageClassName: manual
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data"
