apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: synapse
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
  storageClassName: manual 
  selector:
    matchLabels:
      app: synapse
